/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-06-26 05:35:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.stt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Customer Analysis System</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>고객 상담 분석 시스템</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("      body\r\n");
      out.write("      {\r\n");
      out.write("        max-width: 500px;\r\n");
      out.write("        margin: 2em auto;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      h1\r\n");
      out.write("      {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-family: 'Impact';\r\n");
      out.write("        color: #E95D3C;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      label {\r\n");
      out.write("      \tfont-family: Arial Narrow;\r\n");
      out.write("      \tcolor: #EDA900;\r\n");
      out.write("      \tfont-size: 30px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .button-demo {\r\n");
      out.write("\t\tbackground: #E95D3C;\r\n");
      out.write("    \tcolor: #fff;\r\n");
      out.write("    \tfont-family: Lucida Console;\r\n");
      out.write("    \tfont-size: 15px;\r\n");
      out.write("    \theight: 40px;\r\n");
      out.write("    \twidth: 100px;\r\n");
      out.write("    \tline-height: 25px;\r\n");
      out.write("    \tmargin: 25px 25px;\r\n");
      out.write("    \ttext-align: center;\r\n");
      out.write("    \tborder: 0;\r\n");
      out.write("    \ttransition: all 0.3s ease 0s;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t.button-demo:hover {\r\n");
      out.write(" \t\t background: #EDA900\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t      .buttons-wrapper\r\n");
      out.write("      {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>   \r\n");
      out.write("<body>\r\n");
      out.write("   <h1>Customer Analysis System</h1>\r\n");
      out.write("   <form action=\"index\" method=\"GET\">\r\n");
      out.write("   <div class=buttons-wrapper> \r\n");
      out.write("          <label>Customer  : </label><input type=\"text\" name=\"customer\"><br>\r\n");
      out.write("          <label>Counselor : </label><input type=\"text\" name=\"counsellor\"><br><br>\r\n");
      out.write("          <input class=\"button-demo\" type=\"submit\" value=\"Start\">\r\n");
      out.write("    </div> \r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
